openapi: 3.0.3
info:
  title: Simple EC Backend API
  description: |
    A simple e-commerce backend for comparing Stream/Sequence performance in 1-to-many data export.
    This project is an experimental repository for Advent Calendar article.
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: customers
    description: Customer management
  - name: orders
    description: Order management
  - name: order-items
    description: Order item management
  - name: export
    description: CSV export endpoints

paths:
  /api/orders/{orderId}:
    get:
      tags:
        - orders
      summary: Get order detail by ID
      description: Get order with customer information and order items
      operationId: getOrderDetail
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetailResponse'
        '404':
          description: Order not found

  # Customer endpoints
  /api/v1/customers:
    get:
      tags:
        - customers
      summary: Get all customers
      operationId: getCustomers
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
    post:
      tags:
        - customers
      summary: Create a new customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

  /api/v1/customers/{customerId}:
    get:
      tags:
        - customers
      summary: Get customer by ID
      operationId: getCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Customer not found
    put:
      tags:
        - customers
      summary: Update customer
      operationId: updateCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    delete:
      tags:
        - customers
      summary: Delete customer
      operationId: deleteCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content

  # Order endpoints
  /api/v1/orders:
    get:
      tags:
        - orders
      summary: Get all orders
      operationId: getOrders
      parameters:
        - name: customerId
          in: query
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
    post:
      tags:
        - orders
      summary: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'

  /api/v1/orders/{orderId}:
    get:
      tags:
        - orders
      summary: Get order by ID
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
    put:
      tags:
        - orders
      summary: Update order
      operationId: updateOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
    delete:
      tags:
        - orders
      summary: Delete order
      operationId: deleteOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content

  # Order Items endpoints
  /api/v1/orders/{orderId}/items:
    get:
      tags:
        - order-items
      summary: Get order items by order ID
      operationId: getOrderItems
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderItemResponse'
    post:
      tags:
        - order-items
      summary: Add item to order
      operationId: addOrderItem
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItemRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItemResponse'

  # TODO(#8): OrderItemを単独リソース化しているのは集約境界違反
  # このエンドポイント全体を削除し、/api/orders/{orderId} で対応すべき
  /api/v1/order-items/{itemId}:
    get:
      tags:
        - order-items
      summary: Get order item by ID
      operationId: getOrderItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItemResponse'
    put:
      tags:
        - order-items
      summary: Update order item
      operationId: updateOrderItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItemRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItemResponse'
    delete:
      tags:
        - order-items
      summary: Delete order item
      operationId: deleteOrderItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content

  # Export endpoint (main experimental feature)
  /api/v1/export/orders:
    get:
      tags:
        - export
      summary: Export orders with items as CSV (streaming)
      description: |
        Export orders with their items in CSV format.
        This endpoint is used to compare Kotlin Sequence vs Java Stream vs custom Spliterator
        for handling 1-to-many data expansion.
      operationId: exportOrders
      parameters:
        - name: startDate
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: strategy
          in: query
          description: Export strategy (sequence/stream-flatmap/stream-mapmulti/spliterator)
          required: false
          schema:
            type: string
            enum:
              - sequence
              - stream-flatmap
              - stream-mapmulti
              - spliterator
            default: sequence
      responses:
        '200':
          description: CSV file
          content:
            text/csv:
              schema:
                type: string
                format: binary

components:
  schemas:
    # Order Detail API schemas
    OrderDetailResponse:
      type: object
      required:
        - id
        - customer
        - orderDate
        - totalAmount
        - items
        - createdAt
      properties:
        id:
          type: integer
          format: int64
        customer:
          $ref: '#/components/schemas/CustomerSummary'
        orderDate:
          type: string
          format: date-time
        totalAmount:
          type: number
          format: double
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSummary'
        createdAt:
          type: string
          format: date-time

    CustomerSummary:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string

    OrderItemSummary:
      type: object
      required:
        - id
        - productName
        - quantity
        - unitPrice
      properties:
        id:
          type: integer
          format: int64
        productName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
          format: double

    CustomerRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 255

    CustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time

    OrderRequest:
      type: object
      required:
        - customerId
        - totalAmount
      properties:
        customerId:
          type: integer
          format: int64
        totalAmount:
          type: number
          format: decimal
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemRequest'

    OrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        orderDate:
          type: string
          format: date-time
        totalAmount:
          type: number
          format: decimal
        createdAt:
          type: string
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'

    OrderItemRequest:
      type: object
      required:
        - productName
        - quantity
        - unitPrice
      properties:
        productName:
          type: string
          maxLength: 255
        quantity:
          type: integer
          minimum: 1
        unitPrice:
          type: number
          format: decimal
          minimum: 0

    # TODO(#8): OrderItemを単独リソースとして扱うのは集約境界を破っている
    # /api/v1/order-items/{itemId} エンドポイントとともに見直しが必要
    OrderItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        productName:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
          format: decimal
        createdAt:
          type: string
          format: date-time
